"""
etabs_api_script.py — Generates a Python script that builds the ETABS model
via the CSi ETABS COM API.

The generated script (output/build_etabs_model.py) is intended to be run on
a Windows machine with ETABS 2016+ installed. It uses the comtypes library to
communicate with the ETABS COM server.

Running the script:
  1. Install comtypes:  pip install comtypes
  2. Open ETABS (or let the script open it)
  3. Run:  python build_etabs_model.py
  4. ETABS will build the model and save it as model.edb

References:
  CSi ETABS API Reference Manual (2021)
  Python API Examples — Computers and Structures, Inc.

⚠️  PRELIMINARY MODEL — requires structural engineer review before use.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from structural_elements import (
    ETABSModel,
    ColumnSection,
    WallSection,
    SlabSection,
    ConcreteMaterial,
)
from load_definitions import get_loads, USAGE_LOADS


# ---------------------------------------------------------------------------
# ETABS API constants (from ETABSv1 type library)
# ---------------------------------------------------------------------------

# Units enum (eUnits)
UNITS_KN_M_C = 6    # kN, m, Celsius

# Material types
MAT_CONCRETE = 2

# Load pattern types
LP_DEAD = 1
LP_SUPER_DEAD = 2
LP_LIVE = 3

# Area load direction (gravity = global -Z)
LOAD_DIR_GRAVITY = 10

# Item type
ITEM_OBJ = 0        # apply to named object

# Shell type
SHELL_THIN = 1
PLATE_THIN = 2
SHELL_LAYERED = 3


# ---------------------------------------------------------------------------
# Script generator
# ---------------------------------------------------------------------------

def generate_script(model: ETABSModel, output_edb: str = "model.edb") -> str:
    """
    Return a complete Python script string that builds *model* in ETABS via
    the COM API.

    Args:
        model:       The ETABSModel to encode.
        output_edb:  Path where ETABS will save the .edb file (Windows path).

    Returns:
        Python source code as a string.
    """
    lines: list[str] = []

    def w(*args):
        lines.append(" ".join(str(a) for a in args))

    def blank():
        lines.append("")

    def section(title: str):
        lines.append(f"\n# {'=' * 70}")
        lines.append(f"# {title}")
        lines.append(f"# {'=' * 70}")

    # -----------------------------------------------------------------------
    # Header
    # -----------------------------------------------------------------------
    w('"""')
    w(f"ETABS Model Builder — {model.project_name}")
    w("Generated by etabs_builder (preliminary sizing tool).")
    w()
    w("HOW TO RUN:")
    w("  1. pip install comtypes")
    w("  2. Open or close ETABS — the script will launch it automatically.")
    w(f"  3. python {Path(output_edb).stem}_build.py")
    w(f"  4. Model saved as: {output_edb}")
    w()
    w("⚠️  PRELIMINARY MODEL — NOT FOR CONSTRUCTION")
    w("All element sizes are indicative only. This model has not been designed")
    w("or verified by a structural engineer. Review before any design use.")
    w('"""')
    blank()
    w("import sys")
    w("import comtypes.client")
    blank()

    # -----------------------------------------------------------------------
    # ETABS path — user must update this
    # -----------------------------------------------------------------------
    section("Configuration")
    w("# Update ETABS_EXE to match your installation path")
    w('ETABS_EXE = r"C:\\Program Files\\Computers and Structures\\ETABS 21\\ETABS.exe"')
    w(f'OUTPUT_EDB = r"{output_edb}"')
    blank()

    # -----------------------------------------------------------------------
    # Connect / launch ETABS
    # -----------------------------------------------------------------------
    section("Connect to ETABS")
    w("print('Connecting to ETABS...')")
    w("try:")
    w("    helper = comtypes.client.CreateObject('ETABSv1.Helper')")
    w("    helper = helper.QueryInterface(comtypes.gen.ETABSv1.cHelper)")
    w("    # Try to attach to a running instance first")
    w("    try:")
    w("        myETABS = helper.GetObject('CSI.ETABS.API.ETABSObject')")
    w("        print('  Attached to running ETABS instance.')")
    w("    except Exception:")
    w("        myETABS = helper.CreateObjectPath(ETABS_EXE)")
    w("        myETABS.ApplicationStart()")
    w("        print('  Started new ETABS instance.')")
    w("    SapModel = myETABS.SapModel")
    w("except Exception as e:")
    w("    print(f'ERROR: Could not connect to ETABS: {e}')")
    w("    print('Make sure ETABS is installed and ETABSv1.dll is registered.')")
    w("    sys.exit(1)")
    blank()

    # -----------------------------------------------------------------------
    # Initialise model
    # -----------------------------------------------------------------------
    section("Initialise new model")
    w(f"print('Initialising model: {model.project_name}')")
    w(f"SapModel.InitializeNewModel({UNITS_KN_M_C})  # kN-m-C units")
    w("SapModel.File.NewBlank()")
    w(f"SapModel.SetPresentUnits({UNITS_KN_M_C})")
    blank()

    # -----------------------------------------------------------------------
    # Materials
    # -----------------------------------------------------------------------
    section("Define materials")
    for mat in model.materials:
        w(f"# {mat.label} concrete")
        w(f"ret = SapModel.PropMaterial.SetMaterial('{mat.label}', {MAT_CONCRETE})")
        w(f"ret = SapModel.PropMaterial.SetMPIsotropic(")
        w(f"    '{mat.label}',")
        w(f"    {mat.E_kpa:.3e},  # E (kPa)")
        w(f"    {mat.poisson},    # Poisson")
        w(f"    {mat.thermal:.1e}  # thermal coeff (/°C)")
        w(f")")
        w(f"ret = SapModel.PropMaterial.SetOConcrete_1(")
        w(f"    '{mat.label}',")
        w(f"    {mat.fc_kpa:.0f},  # f'c (kPa)")
        w(f"    False, 0, 1, 0.003, 0, 0  # standard AS3600 params")
        w(f")")
        blank()

    # -----------------------------------------------------------------------
    # Frame sections (columns)
    # -----------------------------------------------------------------------
    section("Define column sections")
    for cs in model.column_sections:
        w_m = cs.width_mm / 1000.0
        d_m = cs.depth_mm / 1000.0
        if cs.shape == "circular":
            w(f"ret = SapModel.PropFrame.SetCircle('{cs.label}', '{cs.material}', {d_m})")
        else:
            w(f"ret = SapModel.PropFrame.SetRectangle('{cs.label}', '{cs.material}', {d_m}, {w_m})")
        w(f"  # {cs.label}: {cs.depth_mm:.0f}mm × {cs.width_mm:.0f}mm, fc={cs.material}")
        blank()

    # -----------------------------------------------------------------------
    # Shell sections (walls and slabs)
    # -----------------------------------------------------------------------
    section("Define wall sections")
    for ws in model.wall_sections:
        thk_m = ws.thickness_mm / 1000.0
        w(f"ret = SapModel.PropArea.SetShell_1(")
        w(f"    '{ws.label}',  # name")
        w(f"    {SHELL_THIN},   # shell-thin (1)")
        w(f"    False,          # exclude bending (False = include)")
        w(f"    '{ws.material}', '{ws.material}',  # membrane, bending material")
        w(f"    0.0,            # angle")
        w(f"    {thk_m},        # membrane thickness (m)")
        w(f"    {thk_m}         # bending thickness (m)")
        w(f")  # {ws.label}: {ws.thickness_mm:.0f} mm wall")
        blank()

    section("Define slab sections")
    for ss in model.slab_sections:
        thk_m = ss.thickness_mm / 1000.0
        w(f"ret = SapModel.PropArea.SetShell_1(")
        w(f"    '{ss.label}',")
        w(f"    {PLATE_THIN},   # plate-thin (2)")
        w(f"    False,")
        w(f"    '{ss.material}', '{ss.material}',")
        w(f"    0.0,")
        w(f"    {thk_m}, {thk_m}")
        w(f")  # {ss.label}: {ss.thickness_mm:.0f} mm slab")
        blank()

    # -----------------------------------------------------------------------
    # Story data
    # -----------------------------------------------------------------------
    section("Define stories")
    w("# Stories are set bottom-up; ETABS internally orders top-down.")
    w("# Using SetStories_2: (story_names, story_heights, is_master, similar,")
    w("#                       splice_above, splice_ht, colors)")
    blank()
    story_names = [lv.name for lv in model.levels]
    story_heights = [lv.height_m for lv in model.levels]
    n_stories = len(model.levels)
    w(f"story_names   = {story_names}")
    w(f"story_heights = {story_heights}")
    w(f"is_master  = ['No'] * {n_stories}")
    w(f"similar    = ['None'] * {n_stories}")
    w(f"splice_above = ['No'] * {n_stories}")
    w(f"splice_ht    = [h / 2 for h in story_heights]")
    w(f"colors       = [16711680] * {n_stories}  # blue")
    blank()
    w("ret = SapModel.Story.SetStories_2(")
    w(f"    {model.base_rl_m},  # base elevation (m RL)")
    w("    story_names, story_heights,")
    w("    is_master, similar, splice_above, splice_ht, colors")
    w(")")
    blank()

    # -----------------------------------------------------------------------
    # Load patterns
    # -----------------------------------------------------------------------
    section("Define load patterns")
    w("# Dead: self-weight multiplier = 1.0")
    w("ret = SapModel.LoadPatterns.Add('Dead', 1, 1.0, True)")
    # Collect unique usages from slabs to create per-usage SDL/Live patterns
    usages_used = sorted({sl.floor_usage for sl in model.slabs})
    for usage in usages_used:
        w(f"ret = SapModel.LoadPatterns.Add('SDL_{usage}', {LP_SUPER_DEAD}, 0.0, True)")
        w(f"ret = SapModel.LoadPatterns.Add('Live_{usage}', {LP_LIVE}, 0.0, True)")
    blank()

    # -----------------------------------------------------------------------
    # Columns
    # -----------------------------------------------------------------------
    section("Add columns")
    w("print('Adding columns...')")
    blank()

    for col in model.columns:
        x_m = col.x_m
        y_m = col.y_m
        for story_name in col.story_names:
            z_bot = model.get_story_base_rl(story_name)
            z_top = model.get_story_rl(story_name)
            obj_name = f"{col.id}_{story_name.replace(' ', '_')}"
            w(f"# Column {col.id} @ ({x_m:.3f}, {y_m:.3f}) — {story_name}")
            w(f"ret, name = SapModel.FrameObj.AddByCoord(")
            w(f"    {x_m:.3f}, {y_m:.3f}, {z_bot:.3f},   # bottom (x, y, z)")
            w(f"    {x_m:.3f}, {y_m:.3f}, {z_top:.3f},   # top    (x, y, z)")
            w(f"    '',  # auto-assign name")
            w(f"    '{col.section_label}',  # section")
            w(f"    '{obj_name}',  # user name")
            w(f"    'Global'  # coordinate system")
            w(f")")
    blank()

    # -----------------------------------------------------------------------
    # Walls
    # -----------------------------------------------------------------------
    section("Add core wall panels")
    w("print('Adding wall panels...')")
    blank()

    for wall in model.walls:
        story_name = wall.story_name
        z_bot = model.get_story_base_rl(story_name)
        z_top = model.get_story_rl(story_name)
        x1, y1 = wall.x1_m, wall.y1_m
        x2, y2 = wall.x2_m, wall.y2_m

        # Vertical wall panel: 4 corners (rectangle in 3D)
        xs = [x1, x2, x2, x1]
        ys = [y1, y2, y2, y1]
        zs = [z_bot, z_bot, z_top, z_top]
        obj_name = wall.id

        w(f"# Wall {wall.id} ({wall.wall_type}) — {story_name}")
        w(f"_xs = {[round(v, 3) for v in xs]}")
        w(f"_ys = {[round(v, 3) for v in ys]}")
        w(f"_zs = {[round(v, 3) for v in zs]}")
        w(f"ret, name = SapModel.AreaObj.AddByCoord(")
        w(f"    4, _xs, _ys, _zs,")
        w(f"    '',  # auto name")
        w(f"    '{wall.section_label}',")
        w(f"    '{obj_name}', 'Global'")
        w(f")")
        blank()

    # -----------------------------------------------------------------------
    # Slabs
    # -----------------------------------------------------------------------
    section("Add slab panels")
    w("print('Adding slab panels...')")
    blank()

    for slab in model.slabs:
        story_name = slab.story_name
        z = model.get_story_rl(story_name)   # slab sits at story's top elevation
        poly = slab.polygon_m
        n = len(poly)
        xs = [round(p[0], 3) for p in poly]
        ys = [round(p[1], 3) for p in poly]
        zs = [round(z, 3)] * n
        usage = slab.floor_usage
        loads = get_loads(usage)
        sdl = loads["sdl_kpa"]
        ll = loads["ll_kpa"]

        w(f"# Slab {slab.id} — {story_name} ({usage})")
        w(f"_xs = {xs}")
        w(f"_ys = {ys}")
        w(f"_zs = {zs}")
        w(f"ret, name = SapModel.AreaObj.AddByCoord(")
        w(f"    {n}, _xs, _ys, _zs,")
        w(f"    '',  # auto name")
        w(f"    '{slab.section_label}',")
        w(f"    '{slab.id}', 'Global'")
        w(f")")
        w(f"slab_name = name if name else '{slab.id}'")
        blank()
        w(f"# Superimposed dead load: {sdl} kPa ({usage})")
        w(f"ret = SapModel.AreaObj.SetLoadUniform(")
        w(f"    slab_name, 'SDL_{usage}', -{sdl},  # negative = gravity direction")
        w(f"    {LOAD_DIR_GRAVITY}, True, 'Global', {ITEM_OBJ}")
        w(f")")
        w(f"# Live load: {ll} kPa ({usage})")
        w(f"ret = SapModel.AreaObj.SetLoadUniform(")
        w(f"    slab_name, 'Live_{usage}', -{ll},")
        w(f"    {LOAD_DIR_GRAVITY}, True, 'Global', {ITEM_OBJ}")
        w(f")")
        blank()

    # -----------------------------------------------------------------------
    # Diaphragm assignments
    # -----------------------------------------------------------------------
    section("Assign rigid diaphragms to slabs")
    w("ret = SapModel.DiaphragmDef.Add('RIGID', 1)  # 1 = Rigid")
    for slab in model.slabs:
        w(f"ret = SapModel.AreaObj.SetDiaphragm('{slab.id}', 'RIGID', {ITEM_OBJ})")
    blank()

    # -----------------------------------------------------------------------
    # Load cases
    # -----------------------------------------------------------------------
    section("Define load cases")
    w("ret = SapModel.LoadCases.StaticLinear.SetCase('Dead')")
    for usage in usages_used:
        w(f"ret = SapModel.LoadCases.StaticLinear.SetCase('SDL_{usage}')")
        w(f"ret = SapModel.LoadCases.StaticLinear.SetCase('Live_{usage}')")
    blank()

    # -----------------------------------------------------------------------
    # Load combinations — AS/NZS 1170.0
    # -----------------------------------------------------------------------
    section("Define load combinations (AS/NZS 1170.0)")
    w("# ULS: 1.2G + 1.5Q  (Eq. 4.2.2a)")
    w("SapModel.RespCombo.Add('ULS_1.2G+1.5Q', 0)  # 0 = linear add")
    w("SapModel.RespCombo.SetCaseList(")
    w("    'ULS_1.2G+1.5Q', 0,")  # 0 = load case
    w("    ['Dead'] + " + str([f"SDL_{u}" for u in usages_used]) + ",")
    w("    [1.2] + [1.2] * " + str(len(usages_used)))
    w(")")
    for usage in usages_used:
        w(f"SapModel.RespCombo.SetCaseList(")
        w(f"    'ULS_1.2G+1.5Q', 0,")
        w(f"    ['Live_{usage}'], [1.5]")
        w(f")")
    blank()
    w("# ULS: 1.35G  (Eq. 4.2.2b — governs for light LL)")
    w("SapModel.RespCombo.Add('ULS_1.35G', 0)")
    w("SapModel.RespCombo.SetCaseList(")
    w("    'ULS_1.35G', 0,")
    w("    ['Dead'] + " + str([f"SDL_{u}" for u in usages_used]) + ",")
    w("    [1.35] + [1.35] * " + str(len(usages_used)))
    w(")")
    blank()
    w("# SLS: 1.0G + 1.0Q  (serviceability)")
    w("SapModel.RespCombo.Add('SLS_1.0G+1.0Q', 0)")
    w("SapModel.RespCombo.SetCaseList(")
    w("    'SLS_1.0G+1.0Q', 0,")
    w("    ['Dead'] + " + str([f"SDL_{u}" for u in usages_used]) + ",")
    w("    [1.0] + [1.0] * " + str(len(usages_used)))
    w(")")
    for usage in usages_used:
        w(f"SapModel.RespCombo.SetCaseList(")
        w(f"    'SLS_1.0G+1.0Q', 0, ['Live_{usage}'], [1.0])")
    blank()

    # -----------------------------------------------------------------------
    # Save
    # -----------------------------------------------------------------------
    section("Save and finish")
    w(f"print('Saving model to: {output_edb}')")
    w(f"ret = SapModel.File.Save(OUTPUT_EDB)")
    w("if ret != 0:")
    w(f"    print(f'WARNING: Save returned code {{ret}}')")
    w("else:")
    w("    print('Model saved successfully.')")
    blank()
    w("print('Build complete.')")
    w("print('Next steps:')")
    w("print('  1. Review model geometry in ETABS 3D view')")
    w("print('  2. Run analysis and check reactions')")
    w("print('  3. Engineer to verify all element sizes and loads')")

    return "\n".join(lines)


def write_script(model: ETABSModel, output_dir: str = "output") -> str:
    """Write the ETABS API script to output_dir and return the file path."""
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    script_path = Path(output_dir) / "build_etabs_model.py"
    edb_path = str(Path(output_dir).resolve() / f"{model.project_name.replace(' ', '_')}.edb")

    script = generate_script(model, edb_path)
    script_path.write_text(script, encoding="utf-8")
    print(f"  ETABS API script → {script_path}")
    return str(script_path)
